### ISSUE TITLE
now what to do when it says finish downloading the new file

### ISSUE THREAD

**Issue by ModGamerBackup** [battlecatsultimate/bcu-assets#3]
it says download finished use this file from now on. how can I open it? well I cant find the screenshot so I will send it later

**Comment by ModGamerBackup** [comment]
also check out my freinds yt his name is brodyman1 yt

**Comment by Xerpyy** [comment]
Please do not ask for unbans on the discord here, and do not advertise either.
After BCU downloads the newest version, simply run that version with java

**Comment by ModGamerBackup** [comment]
BORING....

**Comment by MandarinSmell** [comment]
Our mod already warned you, but if you keep acting like this we will block you from our repository.

I will say one more time. **__Github isn't place where users chat each other. Here is the place where programmers discuss about bug, suggest new feature with code structure.__** It's not for chit chatting. Use Discord or something.

**Comment by ModAltForBCUandBBU** [comment]
Don't bother me play PAS or Pocket Ants Sandbox since I do not know anything about coding I used scratch and I will bee leaving BCU TBC or even my game BBU now if you excuse me I will leave
