### ISSUE TITLE
It would not open when im on windows 11

### ISSUE THREAD

**Issue by ModAltForBCUandBBU** [battlecatsultimate/bcu-assets#5]
the jar file would not open even though i have Java RunTime

**Comment by ModAltForBCUandBBU** [comment]
i also left BBU unupdated

**Comment by MandarinSmell** [comment]
We don't care about your BBU stuffs, just don't bring about that here. Further BBU referring will lead to just blocking no matter what, conidering that you are advertising

Tell us what you tried to open jar file and any pop-up shown when you tried to open it

**Comment by ModAltForBCUandBBU** [comment]
nothing but it does not open

**Comment by MandarinSmell** [comment]
https://docs.google.com/document/d/1zm8wjVBMKz1kL3NoSH29xp9BwagkwwbyibgbZp1UK64/edit?usp=sharing

Try to check if you installed incorrect Java. It can happen if you installed 32bit Java in your computer while your OS is 64bit. After reinstalling it, if that problem still exists, use jarfix below

https://johann.loefflmann.net/en/software/jarfix/index.html

Download jarfix from this link, and run it. Then try to run BCU jar file by double clicking it

I will say in advance that never use `Open with Java` option or your system will connect BCU with `system32` folder

**Comment by MandarinSmell** [comment]
Closing issue due to no further responses or questions
